// This means it must be an array of strings;
var strArr;
var strArr2;
var numArr;
var boolArr;
strArr = ["blue", "blue"];
strArr2 = ["blue", "blue", 100000];
numArr = [11, 99, 100000];
boolArr = [true, false, false];
// You can also define arrays like this:
var strArr3;
var boolArr2;
var numArr2;
strArr3 = ["blue", "blue"];
numArr2 = [11, 99, 100000];
boolArr2 = [true, false, false];
var strNumTuple;
strNumTuple = ["hello", 100];
var myVoid = null;
console.log(myVoid);
