var myString;
var myNum;
var myBol;
var myString2;
var myVar;
var myRandom;
myString = "hi";
myNum = 55;
myBol = true;
myString2 = "hello".slice(0, 2);
myVar = 5;
myRandom = 99;
var myTest = "hello";
console.log(myString);
console.log(myNum);
console.log(myBol);
console.log(myString2);
console.log(myVar);
console.log(myTest);
console.log(myRandom);
